# -*- coding: utf-8 -*-
"""LinearReg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HqW2ZmMSpLrXPwqA6RIi3bbalVRPZC3Y
"""

import pandas as pd
import ipywidgets as widgets
from IPython.display import display
from sklearn.linear_model import LinearRegression

data = {
  'satisfaction': [8, 3, 7, 2, 9, 4, 6, 1],
  'ancienneté':   [5, 1, 8, 2, 10, 3, 6, 1],
  'risque_départ':[0.1, 0.8, 0.2, 0.9, 0.05, 0.7, 0.3, 0.95]
}
df = pd.DataFrame(data)
X = df[['satisfaction', 'ancienneté']]
y = df['risque_départ']
modele = LinearRegression()
modele.fit(X, y)

slider_sat = widgets.IntSlider(
  value=5,                     # valeur de départ
  min=1, max=10, step=1,       # plage de valeurs
  description='Satisfaction',
  style={'description_width': 'initial'}
)

slider_anc = widgets.IntSlider(
  value=5,
  min=1, max=15, step=1,
  description='Ancienneté (ans)',
  style={'description_width': 'initial'}
)

def predire(satisfaction, anciennete):

  nouveau = pd.DataFrame({
    'satisfaction': [satisfaction],
    'ancienneté':   [anciennete]
  })

  risque = modele.predict(nouveau)[0]
  risque = max(0, min(1, risque))  # clamp entre 0 et 1

  if risque >= 0.6:
    niveau = "🔴 Risque ÉLEVÉ"
  elif risque >= 0.35:
    niveau = "🟠 Risque MODÉRÉ"
  else:
    niveau = "🟢 Risque FAIBLE"

  print(f"Satisfaction : {satisfaction}/10")
  print(f"Ancienneté : {anciennete} ans")
  print(f"Formule : 1.073 - (0.098×{satisfaction}) - (0.021×{anciennete})")
  print(f"Résultat : {risque:.0%} {niveau}")

widgets.interact(
  predire,
  satisfaction=slider_sat,
  anciennete=slider_anc
)